CREATE TABLE `match_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `match_id` int(11) NOT NULL,
  `log_id` varchar(20) NOT NULL COMMENT 'logs.tf numeric identifier',
  `map_name` varchar(100) NOT NULL,
  `submitted_by` bigint(20) NOT NULL COMMENT 'Discord user ID who submitted',
  `submitted_at` datetime NOT NULL DEFAULT current_timestamp(),
  `red_team_id` int(11) DEFAULT NULL COMMENT 'Drawbridge team_id that played RED',
  `blu_team_id` int(11) DEFAULT NULL COMMENT 'Drawbridge team_id that played BLU',
  `red_score` int(11) NOT NULL DEFAULT 0,
  `blu_score` int(11) NOT NULL DEFAULT 0,
  `played_at` datetime DEFAULT NULL COMMENT 'When the match was played (from logs.tf date field)',
  `home_overlap` int(11) NOT NULL DEFAULT 0 COMMENT 'Home roster players found in the log',
  `home_roster_size` int(11) NOT NULL DEFAULT 0,
  `away_overlap` int(11) NOT NULL DEFAULT 0 COMMENT 'Away roster players found in the log',
  `away_roster_size` int(11) NOT NULL DEFAULT 0,
  `verified` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Admin-verified flag',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_ml_match` (`match_id`),
  KEY `idx_ml_log` (`log_id`),
  KEY `idx_ml_map` (`map_name`),
  KEY `idx_ml_match_map` (`match_id`, `map_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
